### ISSUE TITLE
Add a wholesome category 

### ISSUE THREAD

**Issue by ThatCopy** [Sv443-Network/JokeAPI#127]
Add a wholesome category with jokes that don't offend anyone. Like with wholesome memes sometimes it's better.

You can use the NSFW filter but you still have a lot of somewhat offensive jokes

**Comment by Sv443** [comment]
Thanks for the suggestion but the categories aren't meant for that. I might implement some sort of whitelist flag filter and some positively themed flags in the future though.

**Comment by Sv443** [comment]
Version 3.0.0 will expand upon the categories, allowing multiple ones to be assigned to each joke and adding many more of them: https://github.com/Sv443-Network/JokeAPI/tree/v3
