### ISSUE TITLE
This API is not RESTful

### ISSUE THREAD

**Issue by cellularmitosis** [Sv443-Network/JokeAPI#529]
When I request an intentionally bogus URL:

```
curl -v https://v2.jokeapi.dev/joke/Anyzzz
```

Instead of a 404, I get a 200 back (or should I call that a 106?):

```
{
    "error": true,
    "internalError": false,
    "code": 106,
    "message": "No matching joke found",
    "causedBy": [
        "No jokes were found that match your provided filter(s)."
    ],
    "additionalInfo": "The specified category/ies is/are invalid. Got: \"anyzzz\" but possible categories are: \"Any, Misc, Programming, Dark, Pun, Spooky, Christmas\" (case insensitive).",
    "timestamp": 1729482966153
}
```

It appears this API eschews HTTP and instead implements a custom protocol on top of HTTP.

For example, the standard way of indicating an internal error is to return a 500.  However, it appears the API would instead return a 200 of the form:

```
{
    "error": true,
    "internalError": true,
    ....
}
```

This is a bummer, because everyone's existing knowledge, frameworks and tooling around handling REST APIs is now useless.

**Comment by cellularmitosis** [comment]
Sorry for venting my frustration.

**Comment by Sv443** [comment]
No I get your frustration, but the API does correctly [implement those status codes.](https://jokeapi.dev/#status-codes)  
If you're getting a 200 on errors, then that's a bug.

**Comment by Sv443** [comment]
Just verified it and yes, that's a bug. It should definitely reply with a 400 on this one:  
  
![image](https://github.com/user-attachments/assets/85e3155e-5638-4660-9665-cade52eb9cb0)

**Comment by Sv443** [comment]
Alright, bug is fixed now. If you didn't open this issue I probably would've never known so thanks!
