### ISSUE TITLE
Change the way jokes are served

### ISSUE THREAD

**Issue by DanBuxton** [Sv443-Network/JokeAPI#535]
## Is your feature request related to a problem? Please describe.
By default explicit and dark jokes are returned causing multiple issues asking to remove them. Example issues: #530, #526, #287 etc (https://github.com/Sv443-Network/JokeAPI/issues?q=is%3Aissue+label%3A%22joke+edit%22+in%3Atitle%3A%22remove%22)

## Describe the solution you'd like
I believe an opt-in basis would be more ethical and sensible considering the nature of some of these jokes. Instead of safe-mode parameter, allow something like ?safe-mode=false

Perhaps for V3, use ``?include=explicit`` and ``?only=explicit,racist`` etc.

**Comment by Sv443** [comment]
Hi, yes this is something that's already on [v3's roadmap.](https://github.com/Sv443-Network/JokeAPI/blob/v3/src/dev/v3.md#what-v3-should-do-better)
